language: csharp
dotnet: 1.0.4
os: linux
dist: trusty
mono: latest
sudo: required

env:
  matrix:
    secure: KJrQ+NfmzlgCSXRyqeAMDGZUG6GO4/+xk1T0wGy1BgVz8seo/fDWL8osWEljB4Sj05sfFj7CM+rociwL6sdVyqCiHbCAM7XuHs58D+4Tlh5pGHL+G1qOl65/pDl0ulq+M7PwDxHPZ60/oyH2a16t5jtD9e4W31y2fXzEbHGLHXg=

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

before_script:
  # https://github.com/dotnet/sdk/issues/335
  - if test "$TRAVIS_OS_NAME" == "osx"; then export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/; else export FrameworkPathOverride=/usr/lib/mono/4.5/; fi
  - mkdir prism/bin
  - export PATH=$PATH:$PWD/prism/bin/
  - ./prism/prism.sh
  - nohup prism run -s https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai_stoplight.json &

script:
  - dotnet restore
  - dotnet build ./src/SendGrid -c Release
  - dotnet test ./tests/SendGrid.Tests/SendGrid.Tests.csproj -c Release -f netcoreapp1.0
  - ls /home/travis/build/sendgrid/sendgrid-csharp/src/SendGrid/bin/Release/net452/
  - ls /home/travis/build/sendgrid/sendgrid-csharp/src/SendGrid/bin/Release/netstandard1.3/
  - dotnet pack ./src/SendGrid -c Release

notifications:
  hipchat:
    rooms:
      secure: T8r/eNzevZXJDmSK7ZKG+t/Vx0cENHIMWVuKbt3RSYbXl6QsWv8UTPamFSkLP0zbcCyGQ7d+QKaEc18ffCtiBV9MXPy8Q1XFGzKxr5/GnwMx4p0ArTqbFLCyl3JuXBmCGouWG+ulb9eOGUFc6L/4p2cwAfXf2oTcXYqosBnfoHg=
    template:
    - '<a href="https://travis-ci.org/%{repository}/builds/%{build_id}">%{repository}
      Build %{build_number}</a> on branch <i>%{branch}</i> by %{author}: <strong>%{message}</strong>
      <a href="https://github.com/%{repository}/commits/%{commit}">View on GitHub</a>'
    format: html
