language: csharp
dotnet: 2.1.803
solution: SendGrid.sln
os: linux
dist: bionic
mono: latest

services:
  - docker

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

script:
  - make test-docker
  - make release

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  skip_cleanup: true
  provider: script
  script: nuget push ./src/SendGrid/bin/Release/SendGrid.*.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
  on:
    branch: master
    tags: true

notifications:
  slack:
    if: branch = master
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: RdE/BGwjr4B5GktjANWdZx2hRcY5GQNQGN9+NxeJ86K2wkTRsQUpPDSj7jXHHUcD9jz+OJHrwWR5Zbun48wE3nD1O/PDs6QNOvYo/isn6PWKGUq6g2XjACPxM34UDRbrma9hGOJTtuEnar64glZEh6xk31bWCpqg/vVxxg/XhWQ=
